Housingsystem
crocomoth/UtopiaCity pull request #14
Opened 2021-07-21 10:18 UTC by madiyarkoishibekov

Tried to implement HousingSystem project according to recent 3 videos. Further will add more "specific" features.

2021-07-23 07:37 UTC, crocomoth requested changes

2021-07-23 07:37 UTC, crocomoth commented on UtopiaCity/Common/Initializers/RealEstateInitializer.cs
> +
Empty lines

2021-07-23 07:37 UTC, crocomoth commented on UtopiaCity/Models/HousingSystem/EstateInfo/EstateAddress.cs
> +        public List<String> District { get; set; }
I don't see how List is required here

2021-07-23 07:37 UTC, crocomoth commented on UtopiaCity/Startup.cs
> + using Microsoft.AspNetCore.Builder;
?

2021-08-02 13:37 UTC, crocomoth approved these changes

2021-08-03 16:30 UTC, AnatoliyDubovtsev approved these changes

2021-08-25 15:02 UTC, closed without merging