Clinic
crocomoth/UtopiaCity pull request #42
Opened 2021-08-26 15:47 UTC by aylmss

added mvc, services, initializer, links at header and at homepage. 

this is a test use case based on EmergencyReport example. additional columns will be added, need to check if correct for now

2021-08-26 17:20 UTC, Ibraga96 commented on UtopiaCity/Data/Migrations/20210826122619_2.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
I think this migration should be removed

2021-08-27 11:36 UTC, crocomoth requested changes

2021-08-27 11:36 UTC, crocomoth commented on UtopiaCity/Common/DbInitializer.cs
>  namespace UtopiaCity.Common
?

2021-08-27 11:36 UTC, crocomoth commented on UtopiaCityTest/UtopiaCityTest.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.15" />
do we need it?

2021-08-27 11:47 UTC, aylmss commented on UtopiaCity/Common/DbInitializer.cs
>  namespace UtopiaCity.Common
deleted, i assume it was a typo

2021-08-27 11:48 UTC, aylmss commented on UtopiaCityTest/UtopiaCityTest.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.15" />
deleted

2021-08-28 09:07 UTC, Ibraga96 approved these changes

2021-08-30 08:09 UTC, crocomoth approved these changes

2021-08-30 09:24 UTC, merged